# DMN - A lightweight domain management service
name: dmn
services:
  dmn:
    image: ghcr.io/v3xlabs/dmn:edge
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dmn
      JWT_SECRET: abc123
      PORKBUN_API_KEY: abc123
      CLOUDFLARE_API_KEY: abc123
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # It is recommended to change this to a more secure password
      POSTGRES_DB: dmn
    ports:
      - "5432:5432"
    volumes:
      - pg-dmn-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg-dmn-data:
   driver: local
