# this is the development environment compose file. See the root directory for the production environment compose file.
name: dmn-dev
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmn
    ports:
      - "5432:5432"
    volumes:
      - pg-dmn-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg-dmn-data:
   driver: local
