install:
	@echo "Setting up pre-commit hook for cargo sqlx prepare..."
	ln -sf ../../.github/pre-commit ../.git/hooks/pre-commit
	chmod +x ../.git/hooks/pre-commit
	@echo "Pre-commit hook installed!" 